# Generated by Django 3.0.6 on 2020-07-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_table',
        ),
        migrations.RenameModel(
            old_name='index',
            new_name='index_table',
        ),
        migrations.RenameModel(
            old_name='services',
            new_name='services_table',
        ),
        migrations.RenameModel(
            old_name='works',
            new_name='works_table',
        ),
    ]
