# Generated by Django 3.0.6 on 2020-07-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0003_works_table_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='subservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('subservice_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
            ],
        ),
    ]
