# Generated by Django 3.0.6 on 2020-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0005_works_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='works_done',
            name='file_name',
            field=models.FileField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
