# Generated by Django 3.0.6 on 2020-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0007_auto_20200729_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works_table',
            name='file_name',
            field=models.FileField(upload_to=''),
        ),
    ]
