# Generated by Django 3.0.6 on 2020-07-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0008_auto_20200729_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works_table',
            name='file_name',
        ),
    ]
